name: Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    if: "! contains(toJSON(github.event.commits.*.message), 'chore(release):')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Verify the build is successful
      - run: npm ci && npm run bootstrap
      - run: npm run build
      - run: npm test

      # Release the next version
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18.0.1
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/github@8.0.2
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@4.6.1
